// <auto-generated />
using System;
using EMS_App.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EMS_App.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231207163612_TableDb")]
    partial class TableDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EMS_App.Models.Event", b =>
                {
                    b.Property<string>("Ename")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EBanner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ediscription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Ename");

                    b.ToTable("Event");
                });

            modelBuilder.Entity("EMS_App.Models.Speaker", b =>
                {
                    b.Property<int>("Sid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Sid"));

                    b.Property<string>("SBio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Simage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Sid");

                    b.ToTable("Speaker");
                });

            modelBuilder.Entity("EMS_App.Models.User", b =>
                {
                    b.Property<string>("Uemail")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Udob")
                        .HasColumnType("datetime2");

                    b.Property<string>("Uname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Unumber")
                        .HasColumnType("int");

                    b.HasKey("Uemail");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
